language: ruby
install:
  gem install bundler --version '1.7'
rvm:
- 1.9.3
- 2.0.0
- 2.1.0
- rbx-2.2.10
- jruby-19mode
- ruby-head
- jruby-head
script:
- bundle exec rspec
addons:
  code_climate:
    repo_token:
      secure: KNVmRK+hN1XzayNTlZIdA8jpkeExMjnSdQwH/eZsJe/7BfHJz5+2t0j7M0iwM+xaN5r2XXoy/fJiqG+DBeUcOIzj5vGaKC9BCjzVoDc81A/lIrYpSd33VN3AeMfltq6eAJYLu66ZgqDhka7fTpJwQ7dPE/sH7S/baYL58oo3FEk=
